"""initial_schema

Revision ID: a274d593a41a
Revises: 
Create Date: 2026-03-15 02:00:01.138465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a274d593a41a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_usage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_usage_ip_address'), ['ip_address'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('template_count', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('template_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('field_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', name='uq_user_template_draft')
    )
    with op.batch_alter_table('template_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_drafts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_drafts_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_drafts_user_id'), ['user_id'], unique=False)

    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('fields_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_id'), ['id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_usage_events_created_at'))

    op.drop_table('usage_events')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_id'))

    op.drop_table('templates')
    with op.batch_alter_table('template_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_drafts_user_id'))
        batch_op.drop_index(batch_op.f('ix_template_drafts_template_id'))
        batch_op.drop_index(batch_op.f('ix_template_drafts_id'))

    op.drop_table('template_drafts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('ip_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_usage_ip_address'))
        batch_op.drop_index(batch_op.f('ix_ip_usage_id'))

    op.drop_table('ip_usage')
    # ### end Alembic commands ###
